### PR TITLE
Fix variable

### PR DESCRIPTION
**Pull request by Daniel-KM**
Hi,

I'm currently checking all my plugins for php 7 and sometimes I find a bug in another one.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

### CODE REVIEW

**Comment by zerocrates** [comment]
@patrickmj If you look at the "fixed variable" commit here, it certainly looks like something that would be a bug in the API import for exhibits. The fix looks correct, but I'd like to be sure this isn't just being worked around somewhere and the fix would break the workaround.

Otherwise it would seem to me that the exhibit API import should be broken whenever there's a child page that gets imported before its parent. Are things being ordered so that the parents always get imported first, or has all the testing just happened to create parents first, then children?

**Comment by patrickmj** [comment]
@zerocrates If I remember and read correctly, when it imports a page, it checks a couple ways for a parent page. If the import data shows a parent page that hasn't yet been imported, it imports it first before saving the child. However, it looks the connection between the child and parent doesn't get saved in that case. So, likely a long-standing bug, but I'll have to look more.

**Comment by patrickmj** [comment]
Pretty sure that the code fixed would never run, based on the updated comment above.

**Comment by zerocrates** [comment]
You can freely reassign parents and children in Exhibit Builder with no regard to which came first, so if it working is relying on that order, I would say it's broken.

**Comment by patrickmj** [comment]
Ah, yes. Was only thinking about top level. Looks like that kind of reordering doesn't happen much. Should be an easy fix.

**Comment by zerocrates** [comment]
It looks like Patrick did the "variable" part of this independently. I'm so-so about moving the conditionals but it doesn't make anything worse for sure, and there's no reason to lose the markup fixes this also does, so let's just go ahead and take the whole thing

**Pull request merged**
